Enable savvy-cli to handle duplicated definitions (#334)

diff --git a/.github/workflows/generate_pkg.yml b/.github/workflows/generate_pkg.yml
--- a/.github/workflows/generate_pkg.yml
+++ b/.github/workflows/generate_pkg.yml
@@ -15,6 +15,22 @@ jobs:
 
       - uses: dtolnay/rust-toolchain@nightly
 
+      - name: check wrapper file generation
+        run: |
+          cargo run --manifest-path ./savvy-cli/Cargo.toml -- update ./R-package/
+
+          # If there's any change, exit with non-zero status
+          # (the code is derived from https://stackoverflow.com/a/3879077)
+          git add ./R-package/
+          git update-index --refresh
+          if ! git diff-index --quiet HEAD -- ./R-package/; then
+            echo
+            echo "some change on wrapper file generation was detected!"
+            echo
+            git diff ./R-package/
+            exit 1
+          fi
+
       - uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true
